### ISSUE TITLE
KeyError: 'arr_1 is not a file in the archive'

### ISSUE THREAD

**Issue by derelearnro** [kentsommer/pytorch-value-iteration-networks#9] opened 2018-09-05 08:51 UTC
python3 train.py --datafile dataset/gridworld_8x8.npz --imsize 8 --lr 0.005 --epochs 30 --k 10 --batch_size 128
Traceback (most recent call last):
  File "train.py", line 135, in <module>
    config.datafile, imsize=config.imsize, train=True, transform=transform)
  File "/home/user/pytorch/tutorials/valueiterationnetworks/pytorch-value-iteration-networks/dataset/dataset.py", line 22, in __init__
    self._process(file, self.train)
  File "/home/user/pytorch/tutorials/valueiterationnetworks/pytorch-value-iteration-networks/dataset/dataset.py", line 49, in _process
    S1 = f['arr_1']
  File "/home/user/miniconda3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 255, in __getitem__
    raise KeyError("%s is not a file in the archive" % key)
KeyError: 'arr_1 is not a file in the archive'

I got this error, could you please

**Comment by kentsommer** [comment] 2019-12-28 07:28
Closing this out as I am not able to reproduce and the issue has aged significantly.

**Closed as completed by kentsommer** 2019-12-28 07:28 UTC
